version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rttm}
      POSTGRES_USER: ${POSTGRES_USER:-rttm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rttm}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rttm}
      POSTGRES_USER: ${POSTGRES_USER:-rttm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rttm}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db_data:
